// Read-only progress telemetry around the installed SDK's Wi-Fi driver.
#include <nds.h>
#include "common/wifi_shared.h"

static volatile u32 * const probe = (volatile u32 *)0x0237f000;
static volatile Wifi_MainStruct *shared;
static bool radio_started, polling;
static unsigned waiting_frames;
static VoidFn card_irq_handler;
bool wifi_card_initted(void);
u32 wifi_card_read_func1_u32(u32 address);
void wifi_card_write_func1_u32(u32 address, u32 value);
u16 wifi_card_mbox0_readpkt(void);
void __real_Wifi_TWL_Update(void);

static void snapshot(void) {
    if (!shared) return;
    probe[8] = shared->curMode;
    probe[9] = shared->reqMode;
    probe[10] = radio_started && wifi_card_initted();
    probe[12] = REG_AUXIE;
    unsigned count = 0;
    for (unsigned i=0; i<WIFI_MAX_AP; i++)
        if (shared->aplist[i].flags & WFLAG_APDATA_ACTIVE) count++;
    probe[17] = count;
}

void __wrap_Wifi_TWL_Update(void) {
    __real_Wifi_TWL_Update();
    snapshot();
}

static void card_irq_probe(void) {
    probe[13]++;
    if (card_irq_handler) card_irq_handler();
    snapshot();
}
void __real_irqSetAUX(u32 mask, VoidFn handler);
void __wrap_irqSetAUX(u32 mask, VoidFn handler) {
    if (mask == BIT(11)) {
        card_irq_handler = handler;
        __real_irqSetAUX(mask, card_irq_probe);
    } else __real_irqSetAUX(mask, handler);
}
void __real_irqEnableAUX(u32 mask);
void __wrap_irqEnableAUX(u32 mask) {
#ifdef PROBE_DROP_WIFI_IRQ
    mask &= ~BIT(11); // Emulator-only lost-interrupt test.
#endif
    __real_irqEnableAUX(mask);
}

// Main-loop fallback: own the receive path after initialization/scan stalls.
// Use the SDK's packet parser; avoid reentering it from an SDIO interrupt.
void wifi_probe_tick(void) {
    if (!radio_started || !shared) return;
    snapshot();
#ifndef PROBE_NO_POLL
    bool waiting = shared->curMode == WIFIMODE_INITIALIZING ||
                   (shared->curMode == WIFIMODE_SCAN && probe[17] == 0);
    if (!polling) {
        waiting_frames = waiting ? waiting_frames+1 : 0;
        if (waiting_frames < 180) return;
        polling = true;
        irqDisableAUX(BIT(11));
    }
    if (shared->curMode == WIFIMODE_DISABLED) return;
    int old_ime = enterCriticalSection();
    probe[11]++;
    u32 irq_status = wifi_card_read_func1_u32(0x400);
    if (irq_status & 1) {
        wifi_card_write_func1_u32(0x400, irq_status);
        for (unsigned i=0; i<8; i++) {
            if (!(wifi_card_read_func1_u32(0x400) & 1)) break;
            if (!wifi_card_mbox0_readpkt()) break;
            probe[14]++;
        }
    }
    __real_Wifi_TWL_Update();
    snapshot();
    leaveCriticalSection(old_ime);
#endif
}
static void mark(u32 stage) {
    probe[0] = stage;
    probe[1] = REG_SCFG_EXT;
    probe[2] = REG_SCFG_CLK;
    u32 sp; __asm__ volatile("mov %0, sp" : "=r"(sp));
    probe[6] = sp;
}
void __real_Wifi_Init(void *data);
void __wrap_Wifi_Init(void *data) {
    shared = data;
    mark(0x20); __real_Wifi_Init(data); mark(0x28);
    // Only SSID is copied into telemetry; passwords and keys remain private.
    volatile u8 *ssid = (volatile u8 *)&probe[20];
    for (unsigned i=0; i<33; i++) ssid[i] = 0;
    if (shared->wfc_number_of_configs) {
        unsigned len = shared->wfc[0].ssid_len;
        if (len > 32) len = 32;
        for (unsigned i=0; i<len; i++) ssid[i] = shared->wfc[0].ssid[i];
        probe[16] = len;
    }
    snapshot();
}
void __real_Wifi_TWL_Init(void);
void __wrap_Wifi_TWL_Init(void) {
    mark(0x22); __real_Wifi_TWL_Init(); mark(0x27);
}
void __real_Wifi_NTR_GetWfcSettings(void);
void __wrap_Wifi_NTR_GetWfcSettings(void) {
    mark(0x23); __real_Wifi_NTR_GetWfcSettings(); mark(0x24);
}
void __real_Wifi_TWL_GetWfcSettings(bool wpa);
void __wrap_Wifi_TWL_GetWfcSettings(bool wpa) {
    mark(0x25);
#ifdef PROBE_FORCE_INIT_WAIT
    // Emulator-only negative control. Never enabled for the delivered ROM.
    while (1) __asm__ volatile("nop");
#endif
    __real_Wifi_TWL_GetWfcSettings(wpa); mark(0x26);
}
void __real_wifi_card_init(void);
void __wrap_wifi_card_init(void) {
    mark(0x30); __real_wifi_card_init(); mark(0x38);
    radio_started = true;
    snapshot();
}
void __real_wifi_sdio_controller_init(void);
void __wrap_wifi_sdio_controller_init(void) {
    mark(0x31); __real_wifi_sdio_controller_init(); mark(0x32);
}
int __real_wifi_card_device_init(void);
// Historical wrapper: same-TU calls in card.twl.c bypass GNU --wrap.
// Connect RAM2 does NOT have reliable 0x33/0x34 coverage. Use the direct
// source instrumentation generated by tools/prepare_native_trace.py instead.
int __wrap_wifi_card_device_init(void) {
    mark(0x33); int result = __real_wifi_card_device_init(); mark(0x34);
    probe[15] = (u32)result; return result;
}
int __real_readFirmware(u32 address, void *destination, u32 size);
int __wrap_readFirmware(u32 address, void *destination, u32 size) {
    probe[3] = address; probe[4] = size; probe[5] = 1;
    int result = __real_readFirmware(address, destination, size);
    probe[18] = (u32)result;
    probe[5] = 2; return result;
}
