cmake_minimum_required(VERSION 3.16)
project(YouTubeDSiEmuTest LANGUAGES C CXX)
set(CMAKE_CXX_STANDARD 17)
set(BUILD_QT_SDL OFF CACHE BOOL "" FORCE)
set(ENABLE_JIT OFF CACHE BOOL "" FORCE)
set(ENABLE_OGLRENDERER OFF CACHE BOOL "" FORCE)
set(ENABLE_GDBSTUB OFF CACHE BOOL "" FORCE)
set(ENABLE_LTO_RELEASE OFF CACHE BOOL "" FORCE)
add_subdirectory(../melonDS-src melonDS)
add_subdirectory(../melonDS-src/src/net/libslirp slirp)
add_executable(emutest main.cpp platform.cpp ../melonDS-src/src/net/Net_Slirp.cpp)
target_include_directories(emutest PRIVATE ../melonDS-src/src ../melonDS-src/src/net)
target_link_libraries(emutest PRIVATE core slirp pthread dl)
