"""Generate HQ2 assets: Galmuri9 Hangul glyph table and top-screen animation.

Inputs (client-hq2/assets): Galmuri9.ttf (SIL OFL 1.1), icon-source.gif (user-supplied art).
Outputs: client-hq2/source/hangul_font.c, client-hq2/source/art.c.
The ROM banner icon is the hand-made client-hq2/assets/yeoltaeng.gif (not generated).
"""
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont, ImageSequence, ImageEnhance, ImageFilter

root = Path(__file__).resolve().parents[1] / 'client-hq2'
assets, source = root / 'assets', root / 'source'
font = ImageFont.truetype(str(assets / 'Galmuri9.ttf'), 10)


def glyph_rows(ch):
    image = Image.new('L', (12, 10))
    ImageDraw.Draw(image).text((0, -1), ch, font=font, fill=255)
    return [sum(int(image.getpixel((x, y)) >= 110) << x for x in range(12)) for y in range(10)]


def c_rows(rows):
    return '{' + ','.join(str(r) for r in rows) + '}'


hangul = [glyph_rows(chr(0xAC00 + i)) for i in range(11172)]
jamo = [glyph_rows(chr(0x3131 + i)) for i in range(94)]
with open(source / 'hangul_font.c', 'w', encoding='ascii') as out:
    out.write('// Galmuri9 Hangul syllables U+AC00..U+D7A3 and compatibility jamo U+3131..U+318E.\n')
    out.write('// Galmuri9, copyright Lee Minseo; SIL OFL 1.1. Generated by tools/make_hq2_assets.py\n')
    out.write('#include <stdint.h>\n')
    out.write('const uint16_t hangul_glyphs[11172][10] = {\n')
    out.write(',\n'.join(c_rows(r) for r in hangul) + '};\n')
    out.write('const uint16_t jamo_glyphs[94][10] = {\n')
    out.write(',\n'.join(c_rows(r) for r in jamo) + '};\n')

# ---- art -------------------------------------------------------------------
frames = [f.convert('RGBA') for f in ImageSequence.Iterator(Image.open(assets / 'icon-source.gif'))]


def clear_background(image):
    """Flood-fill the near-white border background to transparent."""
    image = image.copy()
    w, h = image.size
    px = image.load()
    seen = set()
    stack = [(x, 0) for x in range(w)] + [(x, h - 1) for x in range(w)] + \
            [(0, y) for y in range(h)] + [(w - 1, y) for y in range(h)]
    while stack:
        x, y = stack.pop()
        if (x, y) in seen or not (0 <= x < w and 0 <= y < h):
            continue
        seen.add((x, y))
        r, g, b, a = px[x, y]
        if r > 235 and g > 235 and b > 235:
            px[x, y] = (255, 255, 255, 0)
            stack += [(x + 1, y), (x - 1, y), (x, y + 1), (x, y - 1)]
    return image


clean = [clear_background(f) for f in frames]

# Top screen: 156x156 per frame, composited on the UI background, one shared palette.
ART = 156
BG = (246, 246, 238)  # C(30,30,29) in RGB555, see ui.c
tops = []
for frame in clean:
    canvas = Image.new('RGB', (ART, ART), BG)
    art = frame.resize((ART, ART), Image.LANCZOS)
    canvas.paste(art, (0, 0), art)
    tops.append(canvas)
sheet = Image.new('RGB', (ART, ART * len(tops)))
for i, t in enumerate(tops):
    sheet.paste(t, (0, i * ART))
pal_image = sheet.quantize(colors=255, method=Image.Quantize.MEDIANCUT, kmeans=2)
palette = pal_image.getpalette()[:255 * 3]
indexed = [t.quantize(palette=pal_image, dither=Image.Dither.FLOYDSTEINBERG) for t in tops]


def rgb555(r, g, b):
    return 0x8000 | (r >> 3) | ((g >> 3) << 5) | ((b >> 3) << 10)


with open(source / 'art.c', 'w', encoding='ascii') as out:
    out.write('// Top-screen animation from client-hq2/assets/icon-source.gif (user-supplied).\n')
    out.write('// Generated by tools/make_hq2_assets.py\n#include <stdint.h>\n')
    out.write(f'const unsigned art_size = {ART}, art_frames = {len(indexed)};\n')
    out.write('const uint16_t art_palette[256] = {' +
              ','.join(str(rgb555(*palette[i * 3:i * 3 + 3])) for i in range(255)) + ',32768};\n')
    out.write(f'const uint8_t art_pixels[{len(indexed)}][{ART * ART}] = {{\n')
    for im in indexed:
        data = im.tobytes()
        out.write('{' + ','.join(str(b) for b in data) + '},\n')
    out.write('};\n')

print('assets written:', len(hangul), 'syllables,', len(indexed), 'art frames')
